use_frameworks!

platform :ios, '13.0'

target 'IrohaSwiftSDK_Example' do
  pod 'IrohaSwiftSDK', :path => '../'
  pod 'IrohaSwiftScale', :path => '../'

  target 'IrohaSwiftSDK_Tests' do
    inherit! :search_paths
  end
end
