use_frameworks!

target 'IrohaExample' do
    pod 'IrohaCommunication', :path => '../'
end

target 'IntegrationTestHost' do
    pod 'IrohaCommunication', :path => '../'

    target 'UnitTests' do
        inherit! :search_paths
    end

    target 'IntegrationTests' do
        inherit! :search_paths
    end
end
