# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example-Point' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example-Point

  pod 'KeychainAccess'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'TextFieldEffects'
  pod 'PMAlertController'
  pod 'Toast-Swift'

  target 'Example-PointTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Example-PointUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
