// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: qry_responses.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Account;
@class AccountAsset;
@class AccountAssetResponse;
@class AccountDetailResponse;
@class AccountResponse;
@class Asset;
@class AssetResponse;
@class Block;
@class BlockErrorResponse;
@class BlockResponse;
@class ErrorResponse;
@class RolePermissionsResponse;
@class RolesResponse;
@class SignatoriesResponse;
@class Transaction;
@class TransactionsPageResponse;
@class TransactionsResponse;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ErrorResponse_Reason

typedef GPB_ENUM(ErrorResponse_Reason) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ErrorResponse_Reason_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ErrorResponse_Reason_StatelessInvalid = 0,
  ErrorResponse_Reason_StatefulInvalid = 1,

  /** when requested account does not exist */
  ErrorResponse_Reason_NoAccount = 2,

  /** when requested account asset does not exist */
  ErrorResponse_Reason_NoAccountAssets = 3,

  /** when requested account detail does not exist */
  ErrorResponse_Reason_NoAccountDetail = 4,

  /** when requested signatories does not exist */
  ErrorResponse_Reason_NoSignatories = 5,

  /** when unidentified request was received */
  ErrorResponse_Reason_NotSupported = 6,

  /** when requested asset does not exist */
  ErrorResponse_Reason_NoAsset = 7,

  /** when there are no roles defined in the system */
  ErrorResponse_Reason_NoRoles = 8,
};

GPBEnumDescriptor *ErrorResponse_Reason_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ErrorResponse_Reason_IsValidValue(int32_t value);

#pragma mark - QryResponsesRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface QryResponsesRoot : GPBRootObject
@end

#pragma mark - Asset

typedef GPB_ENUM(Asset_FieldNumber) {
  Asset_FieldNumber_AssetId = 1,
  Asset_FieldNumber_DomainId = 2,
  Asset_FieldNumber_Precision = 3,
};

/**
 * *** WSV data structure *** //
 **/
@interface Asset : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *assetId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *domainId;

@property(nonatomic, readwrite) uint32_t precision;

@end

#pragma mark - Domain

typedef GPB_ENUM(Domain_FieldNumber) {
  Domain_FieldNumber_DomainId = 1,
  Domain_FieldNumber_DefaultRole = 2,
};

@interface Domain : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *domainId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *defaultRole;

@end

#pragma mark - Account

typedef GPB_ENUM(Account_FieldNumber) {
  Account_FieldNumber_AccountId = 1,
  Account_FieldNumber_DomainId = 2,
  Account_FieldNumber_Quorum = 3,
  Account_FieldNumber_JsonData = 4,
};

@interface Account : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *domainId;

@property(nonatomic, readwrite) uint32_t quorum;

@property(nonatomic, readwrite, copy, null_resettable) NSString *jsonData;

@end

#pragma mark - AccountAsset

typedef GPB_ENUM(AccountAsset_FieldNumber) {
  AccountAsset_FieldNumber_AssetId = 1,
  AccountAsset_FieldNumber_AccountId = 2,
  AccountAsset_FieldNumber_Balance = 3,
};

@interface AccountAsset : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *assetId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *accountId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *balance;

@end

#pragma mark - AccountAssetResponse

typedef GPB_ENUM(AccountAssetResponse_FieldNumber) {
  AccountAssetResponse_FieldNumber_AccountAssetsArray = 1,
};

/**
 * *** Responses *** //
 **/
@interface AccountAssetResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<AccountAsset*> *accountAssetsArray;
/** The number of items in @c accountAssetsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger accountAssetsArray_Count;

@end

#pragma mark - AccountDetailResponse

typedef GPB_ENUM(AccountDetailResponse_FieldNumber) {
  AccountDetailResponse_FieldNumber_Detail = 1,
};

@interface AccountDetailResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *detail;

@end

#pragma mark - AccountResponse

typedef GPB_ENUM(AccountResponse_FieldNumber) {
  AccountResponse_FieldNumber_Account = 1,
  AccountResponse_FieldNumber_AccountRolesArray = 2,
};

@interface AccountResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Account *account;
/** Test to see if @c account has been set. */
@property(nonatomic, readwrite) BOOL hasAccount;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *accountRolesArray;
/** The number of items in @c accountRolesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger accountRolesArray_Count;

@end

#pragma mark - AssetResponse

typedef GPB_ENUM(AssetResponse_FieldNumber) {
  AssetResponse_FieldNumber_Asset = 1,
};

@interface AssetResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Asset *asset;
/** Test to see if @c asset has been set. */
@property(nonatomic, readwrite) BOOL hasAsset;

@end

#pragma mark - RolesResponse

typedef GPB_ENUM(RolesResponse_FieldNumber) {
  RolesResponse_FieldNumber_RolesArray = 1,
};

@interface RolesResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *rolesArray;
/** The number of items in @c rolesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger rolesArray_Count;

@end

#pragma mark - RolePermissionsResponse

typedef GPB_ENUM(RolePermissionsResponse_FieldNumber) {
  RolePermissionsResponse_FieldNumber_PermissionsArray = 1,
};

@interface RolePermissionsResponse : GPBMessage

// |permissionsArray| contains |RolePermission|
@property(nonatomic, readwrite, strong, null_resettable) GPBEnumArray *permissionsArray;
/** The number of items in @c permissionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger permissionsArray_Count;

@end

#pragma mark - ErrorResponse

typedef GPB_ENUM(ErrorResponse_FieldNumber) {
  ErrorResponse_FieldNumber_Reason = 1,
  ErrorResponse_FieldNumber_Message = 2,
  ErrorResponse_FieldNumber_ErrorCode = 3,
};

@interface ErrorResponse : GPBMessage

@property(nonatomic, readwrite) ErrorResponse_Reason reason;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@property(nonatomic, readwrite) uint32_t errorCode;

@end

/**
 * Fetches the raw value of a @c ErrorResponse's @c reason property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ErrorResponse_Reason_RawValue(ErrorResponse *message);
/**
 * Sets the raw value of an @c ErrorResponse's @c reason property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetErrorResponse_Reason_RawValue(ErrorResponse *message, int32_t value);

#pragma mark - SignatoriesResponse

typedef GPB_ENUM(SignatoriesResponse_FieldNumber) {
  SignatoriesResponse_FieldNumber_KeysArray = 1,
};

@interface SignatoriesResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *keysArray;
/** The number of items in @c keysArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger keysArray_Count;

@end

#pragma mark - TransactionsResponse

typedef GPB_ENUM(TransactionsResponse_FieldNumber) {
  TransactionsResponse_FieldNumber_TransactionsArray = 1,
};

@interface TransactionsResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Transaction*> *transactionsArray;
/** The number of items in @c transactionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger transactionsArray_Count;

@end

#pragma mark - TransactionsPageResponse

typedef GPB_ENUM(TransactionsPageResponse_FieldNumber) {
  TransactionsPageResponse_FieldNumber_TransactionsArray = 1,
  TransactionsPageResponse_FieldNumber_AllTransactionsSize = 2,
  TransactionsPageResponse_FieldNumber_NextTxHash = 3,
};

typedef GPB_ENUM(TransactionsPageResponse_NextPageTag_OneOfCase) {
  TransactionsPageResponse_NextPageTag_OneOfCase_GPBUnsetOneOfCase = 0,
  TransactionsPageResponse_NextPageTag_OneOfCase_NextTxHash = 3,
};

@interface TransactionsPageResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Transaction*> *transactionsArray;
/** The number of items in @c transactionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger transactionsArray_Count;

@property(nonatomic, readwrite) uint32_t allTransactionsSize;

@property(nonatomic, readonly) TransactionsPageResponse_NextPageTag_OneOfCase nextPageTagOneOfCase;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nextTxHash;

@end

/**
 * Clears whatever value was set for the oneof 'nextPageTag'.
 **/
void TransactionsPageResponse_ClearNextPageTagOneOfCase(TransactionsPageResponse *message);

#pragma mark - QueryResponse

typedef GPB_ENUM(QueryResponse_FieldNumber) {
  QueryResponse_FieldNumber_AccountAssetsResponse = 1,
  QueryResponse_FieldNumber_AccountDetailResponse = 2,
  QueryResponse_FieldNumber_AccountResponse = 3,
  QueryResponse_FieldNumber_ErrorResponse = 4,
  QueryResponse_FieldNumber_SignatoriesResponse = 5,
  QueryResponse_FieldNumber_TransactionsResponse = 6,
  QueryResponse_FieldNumber_AssetResponse = 7,
  QueryResponse_FieldNumber_RolesResponse = 8,
  QueryResponse_FieldNumber_RolePermissionsResponse = 9,
  QueryResponse_FieldNumber_QueryHash = 10,
  QueryResponse_FieldNumber_TransactionsPageResponse = 11,
};

typedef GPB_ENUM(QueryResponse_Response_OneOfCase) {
  QueryResponse_Response_OneOfCase_GPBUnsetOneOfCase = 0,
  QueryResponse_Response_OneOfCase_AccountAssetsResponse = 1,
  QueryResponse_Response_OneOfCase_AccountDetailResponse = 2,
  QueryResponse_Response_OneOfCase_AccountResponse = 3,
  QueryResponse_Response_OneOfCase_ErrorResponse = 4,
  QueryResponse_Response_OneOfCase_SignatoriesResponse = 5,
  QueryResponse_Response_OneOfCase_TransactionsResponse = 6,
  QueryResponse_Response_OneOfCase_AssetResponse = 7,
  QueryResponse_Response_OneOfCase_RolesResponse = 8,
  QueryResponse_Response_OneOfCase_RolePermissionsResponse = 9,
  QueryResponse_Response_OneOfCase_TransactionsPageResponse = 11,
};

@interface QueryResponse : GPBMessage

@property(nonatomic, readonly) QueryResponse_Response_OneOfCase responseOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) AccountAssetResponse *accountAssetsResponse;

@property(nonatomic, readwrite, strong, null_resettable) AccountDetailResponse *accountDetailResponse;

@property(nonatomic, readwrite, strong, null_resettable) AccountResponse *accountResponse;

@property(nonatomic, readwrite, strong, null_resettable) ErrorResponse *errorResponse;

@property(nonatomic, readwrite, strong, null_resettable) SignatoriesResponse *signatoriesResponse;

@property(nonatomic, readwrite, strong, null_resettable) TransactionsResponse *transactionsResponse;

@property(nonatomic, readwrite, strong, null_resettable) AssetResponse *assetResponse;

@property(nonatomic, readwrite, strong, null_resettable) RolesResponse *rolesResponse;

@property(nonatomic, readwrite, strong, null_resettable) RolePermissionsResponse *rolePermissionsResponse;

@property(nonatomic, readwrite, strong, null_resettable) TransactionsPageResponse *transactionsPageResponse;

@property(nonatomic, readwrite, copy, null_resettable) NSString *queryHash;

@end

/**
 * Clears whatever value was set for the oneof 'response'.
 **/
void QueryResponse_ClearResponseOneOfCase(QueryResponse *message);

#pragma mark - BlockResponse

typedef GPB_ENUM(BlockResponse_FieldNumber) {
  BlockResponse_FieldNumber_Block = 1,
};

@interface BlockResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Block *block;
/** Test to see if @c block has been set. */
@property(nonatomic, readwrite) BOOL hasBlock;

@end

#pragma mark - BlockErrorResponse

typedef GPB_ENUM(BlockErrorResponse_FieldNumber) {
  BlockErrorResponse_FieldNumber_Message = 1,
};

@interface BlockErrorResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

#pragma mark - BlockQueryResponse

typedef GPB_ENUM(BlockQueryResponse_FieldNumber) {
  BlockQueryResponse_FieldNumber_BlockResponse = 1,
  BlockQueryResponse_FieldNumber_BlockErrorResponse = 2,
};

typedef GPB_ENUM(BlockQueryResponse_Response_OneOfCase) {
  BlockQueryResponse_Response_OneOfCase_GPBUnsetOneOfCase = 0,
  BlockQueryResponse_Response_OneOfCase_BlockResponse = 1,
  BlockQueryResponse_Response_OneOfCase_BlockErrorResponse = 2,
};

@interface BlockQueryResponse : GPBMessage

@property(nonatomic, readonly) BlockQueryResponse_Response_OneOfCase responseOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) BlockResponse *blockResponse;

@property(nonatomic, readwrite, strong, null_resettable) BlockErrorResponse *blockErrorResponse;

@end

/**
 * Clears whatever value was set for the oneof 'response'.
 **/
void BlockQueryResponse_ClearResponseOneOfCase(BlockQueryResponse *message);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
